export * from './appointment';
export * from './home';
export * from './login';
export * from './nav';
export * from './patient';
export * from './prescription';
export * from './register';
export * from './pharmacies';
export * from './allergyform';